name: PSHologramm
version: 1.1.0
main: org.qweyns.pshologramm.PSHologramm
api-version: '1.21'
author: qweyns

depend:
  - ProtectionStones
  - WorldGuard
softdepend:
  - DecentHolograms
  - FancyHolograms
  - Vault
  - PlayerPoints
  - PlaceholderAPI

commands:
  pshologramm:
    description: Основная команда плагина
    permission: pshologramm.admin
    aliases: [psh]
  psholo-api:
    description: API команда для интеграции сторонних меню
    permission: pshologramm.admin
